################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
BoardSupportPackage/src/AsciiLib.obj: C:/Users/Alex\ Perera/Desktop/uP2/uP2_lab5/BoardSupportPackage/src/AsciiLib.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv7/ccs_base/arm/include" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/board" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/cc3100_usage" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/SL_Common" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/spi_cc3100" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/simplelink/include" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Libraries/CC3100SupportPackage" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/G8RTOS_Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/BoardSupportPackage/DriverLib" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/BoardSupportPackage/inc" --include_path="C:/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Lab5" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/AsciiLib.d" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BoardSupportPackage/src/BSP.obj: C:/Users/Alex\ Perera/Desktop/uP2/uP2_lab5/BoardSupportPackage/src/BSP.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv7/ccs_base/arm/include" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/board" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/cc3100_usage" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/SL_Common" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/spi_cc3100" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/simplelink/include" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Libraries/CC3100SupportPackage" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/G8RTOS_Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/BoardSupportPackage/DriverLib" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/BoardSupportPackage/inc" --include_path="C:/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Lab5" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/BSP.d" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BoardSupportPackage/src/BackChannelUart.obj: C:/Users/Alex\ Perera/Desktop/uP2/uP2_lab5/BoardSupportPackage/src/BackChannelUart.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv7/ccs_base/arm/include" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/board" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/cc3100_usage" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/SL_Common" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/spi_cc3100" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/simplelink/include" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Libraries/CC3100SupportPackage" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/G8RTOS_Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/BoardSupportPackage/DriverLib" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/BoardSupportPackage/inc" --include_path="C:/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Lab5" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/BackChannelUart.d" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BoardSupportPackage/src/ClockSys.obj: C:/Users/Alex\ Perera/Desktop/uP2/uP2_lab5/BoardSupportPackage/src/ClockSys.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv7/ccs_base/arm/include" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/board" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/cc3100_usage" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/SL_Common" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/spi_cc3100" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/simplelink/include" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Libraries/CC3100SupportPackage" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/G8RTOS_Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/BoardSupportPackage/DriverLib" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/BoardSupportPackage/inc" --include_path="C:/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Lab5" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/ClockSys.d" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BoardSupportPackage/src/Joystick.obj: C:/Users/Alex\ Perera/Desktop/uP2/uP2_lab5/BoardSupportPackage/src/Joystick.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv7/ccs_base/arm/include" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/board" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/cc3100_usage" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/SL_Common" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/spi_cc3100" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/simplelink/include" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Libraries/CC3100SupportPackage" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/G8RTOS_Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/BoardSupportPackage/DriverLib" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/BoardSupportPackage/inc" --include_path="C:/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Lab5" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/Joystick.d" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BoardSupportPackage/src/LCD.obj: C:/Users/Alex\ Perera/Desktop/uP2/uP2_lab5/BoardSupportPackage/src/LCD.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv7/ccs_base/arm/include" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/board" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/cc3100_usage" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/SL_Common" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/spi_cc3100" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/simplelink/include" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Libraries/CC3100SupportPackage" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/G8RTOS_Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/BoardSupportPackage/DriverLib" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/BoardSupportPackage/inc" --include_path="C:/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Lab5" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/LCD.d" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BoardSupportPackage/src/LED.obj: C:/Users/Alex\ Perera/Desktop/uP2/uP2_lab5/BoardSupportPackage/src/LED.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv7/ccs_base/arm/include" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/board" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/cc3100_usage" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/SL_Common" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/spi_cc3100" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/simplelink/include" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Libraries/CC3100SupportPackage" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/G8RTOS_Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/BoardSupportPackage/DriverLib" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/BoardSupportPackage/inc" --include_path="C:/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Lab5" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/LED.d" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BoardSupportPackage/src/bme280.obj: C:/Users/Alex\ Perera/Desktop/uP2/uP2_lab5/BoardSupportPackage/src/bme280.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv7/ccs_base/arm/include" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/board" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/cc3100_usage" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/SL_Common" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/spi_cc3100" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/simplelink/include" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Libraries/CC3100SupportPackage" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/G8RTOS_Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/BoardSupportPackage/DriverLib" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/BoardSupportPackage/inc" --include_path="C:/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Lab5" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/bme280.d" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BoardSupportPackage/src/bme280_support.obj: C:/Users/Alex\ Perera/Desktop/uP2/uP2_lab5/BoardSupportPackage/src/bme280_support.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv7/ccs_base/arm/include" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/board" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/cc3100_usage" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/SL_Common" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/spi_cc3100" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/simplelink/include" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Libraries/CC3100SupportPackage" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/G8RTOS_Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/BoardSupportPackage/DriverLib" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/BoardSupportPackage/inc" --include_path="C:/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Lab5" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/bme280_support.d" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BoardSupportPackage/src/bmi160.obj: C:/Users/Alex\ Perera/Desktop/uP2/uP2_lab5/BoardSupportPackage/src/bmi160.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv7/ccs_base/arm/include" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/board" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/cc3100_usage" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/SL_Common" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/spi_cc3100" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/simplelink/include" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Libraries/CC3100SupportPackage" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/G8RTOS_Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/BoardSupportPackage/DriverLib" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/BoardSupportPackage/inc" --include_path="C:/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Lab5" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/bmi160.d" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BoardSupportPackage/src/bmi160_support.obj: C:/Users/Alex\ Perera/Desktop/uP2/uP2_lab5/BoardSupportPackage/src/bmi160_support.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv7/ccs_base/arm/include" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/board" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/cc3100_usage" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/SL_Common" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/spi_cc3100" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/simplelink/include" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Libraries/CC3100SupportPackage" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/G8RTOS_Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/BoardSupportPackage/DriverLib" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/BoardSupportPackage/inc" --include_path="C:/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Lab5" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/bmi160_support.d" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BoardSupportPackage/src/demo_sysctl.obj: C:/Users/Alex\ Perera/Desktop/uP2/uP2_lab5/BoardSupportPackage/src/demo_sysctl.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv7/ccs_base/arm/include" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/board" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/cc3100_usage" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/SL_Common" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/spi_cc3100" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/simplelink/include" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Libraries/CC3100SupportPackage" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/G8RTOS_Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/BoardSupportPackage/DriverLib" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/BoardSupportPackage/inc" --include_path="C:/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Lab5" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/demo_sysctl.d" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BoardSupportPackage/src/i2c_driver.obj: C:/Users/Alex\ Perera/Desktop/uP2/uP2_lab5/BoardSupportPackage/src/i2c_driver.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv7/ccs_base/arm/include" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/board" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/cc3100_usage" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/SL_Common" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/spi_cc3100" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/simplelink/include" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Libraries/CC3100SupportPackage" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/G8RTOS_Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/BoardSupportPackage/DriverLib" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/BoardSupportPackage/inc" --include_path="C:/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Lab5" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/i2c_driver.d" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BoardSupportPackage/src/opt3001.obj: C:/Users/Alex\ Perera/Desktop/uP2/uP2_lab5/BoardSupportPackage/src/opt3001.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv7/ccs_base/arm/include" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/board" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/cc3100_usage" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/SL_Common" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/spi_cc3100" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/simplelink/include" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Libraries/CC3100SupportPackage" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/G8RTOS_Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/BoardSupportPackage/DriverLib" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/BoardSupportPackage/inc" --include_path="C:/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Lab5" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/opt3001.d" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BoardSupportPackage/src/tmp007.obj: C:/Users/Alex\ Perera/Desktop/uP2/uP2_lab5/BoardSupportPackage/src/tmp007.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccsv7/ccs_base/arm/include" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/board" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/cc3100_usage" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/SL_Common" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/spi_cc3100" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/CC3100SupportPackage/simplelink/include" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Libraries/CC3100SupportPackage" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/G8RTOS_Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/BoardSupportPackage/DriverLib" --include_path="C:/Users/Alex Perera/Desktop/uP2/Libraries/BoardSupportPackage/inc" --include_path="C:/ti/ccsv7/ccs_base/arm/include/CMSIS" --include_path="C:/Users/Alex Perera/Desktop/uP2/uP2_lab5/Lab5" --include_path="C:/Users/Alex Perera/Desktop/uP2/Github_repo/Lab5" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/tmp007.d" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


